###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Caio",
    "senha": "12345"
}

###

PUT http://localhost:3000/usuarios/3
Content-Type: application/json

{
    "nome": "GamesEdu",
    "senha": "Olha_que_geometria"
}
###

DELETE http://localhost:3000/usuarios/10